#!/usr/bin/env bun
// Pre-build step: embed src/public/animation.js as gzip bytes (base64).
// Runtime can serve gzip directly and inflate for legacy clients.

import { createHash } from "node:crypto";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

const IN_FILE = join(import.meta.dir, "..", "src", "public", "animation.js");
const OUT_FILE = join(import.meta.dir, "..", "src", "public", "animation-embedded.ts");

const rawBytes = Buffer.from(await Bun.file(IN_FILE).arrayBuffer());
const gzipBytes = gzipSync(rawBytes, { level: 9 });
const sha1 = createHash("sha1").update(rawBytes).digest("hex");

const content = `// AUTO-GENERATED by scripts/embed-animation.ts - do not edit by hand.
// Source: src/public/animation.js

export const ANIMATION_RAW_SHA1 = ${JSON.stringify(sha1)};
export const ANIMATION_RAW_LENGTH = ${rawBytes.length};
export const ANIMATION_GZIP_LENGTH = ${gzipBytes.length};
export const ANIMATION_GZIP_B64 = ${JSON.stringify(gzipBytes.toString("base64"))};
`;

await Bun.write(OUT_FILE, content);

const ratio = ((1 - gzipBytes.length / rawBytes.length) * 100).toFixed(2);
console.log(
  `Embedded animation: raw ${(rawBytes.length / 1024).toFixed(0)} KB -> gzip ${(gzipBytes.length / 1024).toFixed(0)} KB (${ratio}% smaller).`
);
console.log(`Wrote ${OUT_FILE}`);
