#!/usr/bin/env bun
// Pre-build step: pack src/public/logos/*.png into a brotli-compressed bundle.
// Runtime serves logos from this packed payload to keep single-binary offline mode.

import { createHash } from "node:crypto";
import { readdirSync } from "node:fs";
import { join } from "node:path";
import { brotliCompressSync, constants as zlibConstants } from "node:zlib";

const LOGO_DIR = join(import.meta.dir, "..", "src", "public", "logos");
const OUT_FILE = join(import.meta.dir, "..", "src", "web", "logos-embedded.ts");

const files = readdirSync(LOGO_DIR).filter((f) => f.endsWith(".png")).sort();

const chunks: Buffer[] = [];
const entries: string[] = [];
let offset = 0;
let rawTotal = 0;
let compressedTotal = 0;

for (const filename of files) {
  const rawBytes = Buffer.from(await Bun.file(join(LOGO_DIR, filename)).arrayBuffer());
  const compressed = brotliCompressSync(rawBytes, {
    params: {
      [zlibConstants.BROTLI_PARAM_QUALITY]: 11,
      [zlibConstants.BROTLI_PARAM_MODE]: zlibConstants.BROTLI_MODE_GENERIC,
    },
  });
  const sha1 = createHash("sha1").update(rawBytes).digest("hex");

  chunks.push(compressed);
  entries.push(
    `  ${JSON.stringify(filename)}: { offset: ${offset}, compressedLength: ${compressed.length}, rawLength: ${rawBytes.length}, sha1: ${JSON.stringify(sha1)} },`
  );

  offset += compressed.length;
  rawTotal += rawBytes.length;
  compressedTotal += compressed.length;
}

const pack = Buffer.concat(chunks);
const packB64 = pack.toString("base64");

const content = `// AUTO-GENERATED by scripts/embed-logos.ts - do not edit by hand.
// Source: src/public/logos/*.png

export interface LogoPackedEntry {
  offset: number;
  compressedLength: number;
  rawLength: number;
  sha1: string;
}

export const LOGO_PACK_B64 = ${JSON.stringify(packB64)};

export const LOGO_INDEX: Record<string, LogoPackedEntry> = {
${entries.join("\n")}
};

export const LOGO_RAW_TOTAL_BYTES = ${rawTotal};
export const LOGO_PACK_TOTAL_BYTES = ${compressedTotal};
`;

await Bun.write(OUT_FILE, content);

const ratio = rawTotal > 0 ? ((1 - compressedTotal / rawTotal) * 100).toFixed(2) : "0.00";
console.log(
  `Embedded ${files.length} logos: raw ${(rawTotal / 1024).toFixed(0)} KB -> pack ${(compressedTotal / 1024).toFixed(0)} KB (${ratio}% smaller).`
);
console.log(`Wrote ${OUT_FILE}`);
